name = "BagOfWords"
uuid = "87b137f8-3b59-4550-8c54-1b47926674ff"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
